### ISSUE TITLE
Documentation clarifications

### ISSUE THREAD

**Issue by samuelweiler** [w3c/onboarding#1]
To elucidate "the W3C identifier for your group", could you provide a link to the list of those for existing groups?  Or otherwise explain what is meant?  (Many just add the word "numeric"?)

Is this also what is meant by "your group's id"?  (Glancing at one of the Privacy IG's specs, it's not clear what you mean.)

**Comment by caribouW3** [comment]
I referred to the W3C API instead of patent status (which would not be a valid advice for CGs anyway) and started an FAQ with this question (the group pages no longer make this id visible, unfortunately)
