### ISSUE TITLE
What happens when a group closes?

### ISSUE THREAD

**Issue by koalie** [w3c/onboarding#14]
Hi @caribouW3 

Do chairs/team contacts need to keep track of their automatic onboarding trigger in the case that the group (or community/business group) closes? or it is there a report sent elsewhere about a discrepancy that causes someone on the team to remove the no longer necessary trigger?

**Comment by caribouW3** [comment]
Hi,
Thanks for raising this issue.
If a group closes it is no longer possible to join it, so there will be no more POSTs from the webhook. However, I have not implemented any check to verify whether templates in this repository belong to open groups and clean up the dangling ones.
I will consider making a small tool to keep things clean.

**Comment by samuelweiler** [comment]
I like @caribouW3's answer.  I'm also thinking of the edge case of a group that closes and is reopened.  Since people can't join it while closed, I'm not particularly concerned - and it might be nice to have the onboarding message there if the group is reopened.

**Comment by caribouW3** [comment]
FWIW, I've added a note to the team wiki about "how to start a group" on the possibility to create a welcome message in the onboarding tool.
