### ISSUE TITLE
Possible to include more info in the text of the email?

### ISSUE THREAD

**Issue by wseltzer** [w3c/onboarding#3]
Thanks for this onboarding flow! A few editorial comments in https://github.com/w3c/onboarding/pull/2

Would it be possible to include some preview of the generated "facility map" in the email itself? I recognize that it's better to send people to the dynamically generated page, but for people who don't automatically click links in email, or have email available for more ready reference and search, can we include at least the topic headers that will be shown there?

**Comment by caribouW3** [comment]
I suppose that sending a snapshot of the content would somewhat defeat the purpose, which is mostly that people bookmark this as a future reference. However, adding a summary of the content in the template is a good idea.
