### ISSUE TITLE
Numeric IDs

### ISSUE THREAD

**Issue by svgeesus** [w3c/onboarding#32]
Two points:

**1) Finding the pesky numeric id.** 

From the FAQ:

> **I don't know my group's id, how do I find it?**

> It is the same numeric id that you use for links to Patent status in specs (links from https://www.w3.org/2004/01/pp-impl/).

That used to be true, but now they have sensible names like [https://www.w3.org/groups/wg/audio/ipr](https://www.w3.org/groups/wg/audio/ipr)

> you can find it in other tools e.g. https://www.w3.org/PM/Groups/browse.html (choose your group in the drop-down menu

![image](https://user-images.githubusercontent.com/2506926/213458865-9c42fddf-88ce-48d5-aa8a-71baa759c0e0.png)

That page seems to be broken, the dropdown has a single entry `{$name}`. Maybe an API changed or a service needs to be restarted?

> or https://w3c.github.io/Guide/participant/group.html.

Also broken

![image](https://user-images.githubusercontent.com/2506926/213458726-fad45738-d472-4a4e-8777-ca716e84b1d9.png)

**2) Advisability of numeric ids**

This directory listing is fairly off-putting. I would far rather see a list of actual WG names like we use everywhere else.

![image](https://user-images.githubusercontent.com/2506926/213459374-da24f356-01ed-4690-a4b5-d3bb6f297b11.png)

**Comment by svgeesus** [comment]
@caribouW3

**Comment by plehegar** [comment]
We need to move away from numeric IDs. The W3C API provides all of the necessary bits.

@caribouW3 , can you bring this higher in your TODO list?

**Comment by caribouW3** [comment]
done and deployed

**Comment by svgeesus** [comment]
Perfect, thanks!
