### ISSUE TITLE
group.shorttype

### ISSUE THREAD

**Issue by plehegar** [w3c/onboarding#38]
it would be nice to write something like:
  https://auth.w3.org/?url=https://www.w3.org/groups/{{ group.shorttype }}/{{ group.shortname }}/calendar

**Comment by plehegar** [comment]
@caribouW3 , let me know if you'd like me to write a PR for this.

**Comment by caribouW3** [comment]
Actually, there is already a group.type value (currently used in the default template).
We can do something like 
{% if group.type == 'working group'}
   {% set shorttype = 'wg' %}
{% else %}
    {% set shorttype = 'ig' %}
{%endif}
then use the {{shorttype}} variable.

I'll open a separate issue to revamp the default template.
