### ISSUE TITLE
Revamp the default welcome message

### ISSUE THREAD

**Issue by caribouW3** [w3c/onboarding#42]
This is a more generic issue about crafting a better default message for WGs and IGs, possibly
referring to the /groups/.../... uris instead of  https://w3c.github.io/Guide/participant/group.html?gid=...
(this issue is a followup to issue #38 )

Feel free to give ideas.

It is also possible to discuss a default message for all CGs.

**Comment by vivienlacourba** [comment]
> This is a more generic issue about crafting a better default message for WGs and IGs, possibly
referring to the /groups/.../... uris instead of https://w3c.github.io/Guide/participant/group.html?gid=...

I agree and overall +1 to the changes you brought in the merge request #44.
