### ISSUE TITLE
CEPC link

### ISSUE THREAD

**Issue by plehegar** [w3c/onboarding#50]
CEPC link is now:
  https://www.w3.org/policies/code-of-conduct/

A general pull request to update that link seems the most efficient.

fyi @koalie

**Comment by koalie** [comment]
sounds good to me! Thank you 🙏

**Comment by caribouW3** [comment]
Already changed in the default template

**Comment by plehegar** [comment]
> Already changed in the default template

s/W3C Code of Ethics and Professional Conduct (CEPC)/W3C Code of Conduct/

**Comment by plehegar** [comment]
A lot of templates still use the old link/names.
